### ISSUE TITLE
Normalization Constraint on Capillarity Vectors

### ISSUE THREAD

**Issue by sgbaird** [Yufeng-shen/TJ2GBE#6]
Hi Yufeng,

Thanks for all of your help earlier. Had a question about your method. Where does the normalization constraint ||X||^2 = 1 (eqn 3) come from? Any references I could look at for this?

Sterling

**Comment by Yufeng-shen** [comment]
Basically, that's because these "triple junction geometry based methods" can only determine the energy up to a constant factor. If you multiply a constant factor to all the capillary vectors, all the Herring's equations at all triple junctions still hold. Therefore the reconstructed GBED has arbitrary unit, they only show the anisotropy of the energy, not the absolute value. So we can use the normalization constraint to avoid the trivial minimizer (X=0). The previous paper  "Method to calculate the grain boundary energy distribution over the space of macroscopic boundary parameters from the geometry of triple junctions" by Morawiec also takes similar normalization step.

**Comment by sgbaird** [comment]
That makes a lot of sense. Is there a particular reason for using the 2-norm that you know of, rather than another constraint?

**Comment by Yufeng-shen** [comment]
That's a great question. I believe using a different norm will affect the final results, but the effects should be very small (comparing to other noises). I chose 2-norm just because it is easier to compute.

**Comment by sgbaird** [comment]
Awesome, that helps. Thanks Yufeng!
